---
# GitHub Action Workflow file to print the Hello World
name: Hello World!
on: 
  push: 
    branches:
      - master

jobs: 
  hello_world_job: 
    runs-on: ubuntu-latest
    steps: 
      - name: Say Hello 
        run: |
          echo "Hello Peeps ;D"

  Date_and_Time: 
    runs-on: ubuntu-18.04
    steps: 
      - name: Print Date and Time
        run: |
          date
        
  Repo: 
    runs-on: ubuntu-latest
    steps: 
      - name: What we have in Repo
        run: |
          ls