---
name: Deploy

on: 
  push: 
    branches: 
      - master

jobs: 
  build: 
    runs-on: ubuntu-18.04
    steps: 
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with: 
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: black-cicd
          heroku_email: ${{secrets.EMAIL}}
          healthcheck: "https://black-cicd.herokuapp.com/health"
          checkstring: "ok"
          delay: 5
          rollbackonhealthcheckfailed: true
...