---
# The Environment Setup and Linting Workflow
name: "Simple Deployment"
on: 
  push: 
    branches:
      - master

jobs: 
  Simple_Deployment_Job: 
    runs-on: ubuntu-18.04
    steps: 
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: '12.x'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
...